name: Deploy in k8s
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - master

jobs:
  build:
    # Job name is Greeting
    name: Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: twitterbuben/bible-bot
          tags: latest,${{github.sha}}
          registry: harbor.seschi98.cloud
      # - name: Trigger k8s deployment
      #   uses: steebchen/kubectl@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #   with:
      #     args: set image -n goldau-website --record deployment/frontend frontend=harbor.seschi98.cloud/goldau/frontend:${{ github.sha }}
      # - name: verify deployment
      #   uses: steebchen/kubectl@master
      #   env:
      #     KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
      #   with:
      #     args: '"rollout status deployment/frontend -n goldau-website"'